sirrus233/wotr-community-website

frontend/package-lock.json

npm update

---

frontend/src/GameReportForm.tsx

The bones of form validation! Including:
- Introducing an overall validation pattern
- Simple validation of top-level required fields, to demonstrate the pattern works
It's very long, sorry. Once this foundation is in it should be easier to make PRs more bite-sized 😬

Set up form validation

---

frontend/src/types.ts

Add a type for planned game report payload

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/DataField.hs
backend/src/Types/Database.hs
backend/src/Validation.hs
frontend/src/hooks/useFormData.tsx

Does what it says on the tin!
This is a *very* basic `submitReport` API. No bells or whistles attached, but I was able to confirm I can send a report from the frontend to the backend!

Basic API for submit report

---

README.md
backend/README.md
frontend/README.md

Some nice things for us! Left the backend README just a skeleton since none of the Rust setup will apply.

Add some READMEs

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Validation.hs

Now that the base work is done, gonna try to have these be somewhat more reasonable in size!
This changes the submitReport api to actually return the (processed) submitted report.

Return submitted report from submit api

---

backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/Database.hs
backend/wotr-community-website.cabal

Record wildcard syntax make less word

---

frontend/src/GameReportForm.tsx
frontend/src/MultiOptionInput.tsx
frontend/src/SingleOptionInput.tsx
frontend/src/constants.ts

The title! Tested it on the other branch and the server accepts all stronghold values after adding this mapping.

Map stronghold and expansion values to display labels

---

backend/src/AppServer.hs

We have two functions for getting a player's stats - one retrieves the most recent stats from any year, the other retrieves only stats for a specified year (rolling over stats from a prior year if need-be). I used the former, but should have been the latter (since we're always submitting for the current year).

Bugfix - Read correct player stats

---

backend/src/AppServer.hs

Title - just a small revision, no functional changes

Small cosmetic refactor

---

backend/src/Validation.hs

Validation bugfix

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/Api.hs

It does the thing! Pretty self-explanatory, I should think. And perhaps the last of the major APIs we need???

Leaderboard API

---

frontend/src/GameReportForm.tsx
frontend/src/hooks/useFormData/index.tsx

Add loading state to game report form

---

frontend/src/constants.ts
frontend/src/hooks/useFormData/index.tsx
frontend/src/types.ts

Some minimal error handling. I took a stab at language for the 422 error message mapping, but I'm 0% attached to what I wrote if you want to customize those at all. This might technically be the last MVP item for the form, so will switch to other frontend pages from here!

Display game report submission errors

---

frontend/src/Rankings.tsx

Took me a sad amount of time to realize this was part of the reason the server doesn't like me, that's my queue to go to bed 😂

Update leaderboard endpoint in frontend

---

frontend/src/Rankings.tsx

Also fixes the wonky horizontal scrolling, accidentally had two `overflow: auto`s in there

Style leaderboard a little bit

---

frontend/package-lock.json
frontend/package.json
frontend/src/GameReportForm.tsx
frontend/webpack.config.js

Barad-what??
It's nearly 2025, so let's render utf-8 chars properly! Also added the proper accent to "Lórien", since we can display it now.

Fix encoding issue

---

frontend/src/GameReportForm.tsx
frontend/src/VictoryPoints.tsx
frontend/src/utils.tsx

Need to reuse these for the game reports view

Move frontend mapping utils to common location

---

backend/bin/deploy.sh
frontend/bin/deploy.sh

Dir-agnostic FE deploy

---

frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/webpack.config.js

Now with 100% less frontend-developer

Actually fix encoding

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx

First pass, pretty sure I got everything noted in the issue except for youtube channels and tournament schedules - those could be round 2?
I completely made up the little disclaimer under Community Resources, idk what the right legalese is for that 🤷‍♀️

Site header and landing page

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/Api.hs

Per discussion, this won't be admin-locked until we build auth capability.

renamePlayer API

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Types/Api.hs

This one's a little less trivial, but should do all the needful. It needs to be tested still - that's a little annoying without frontend support, so YOLO for now!

Modify report API

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/Api.hs

Tested this one, works a treat! Measured the time it takes to reprocessing reports as ~roughly 10 seconds. We can probably get that down by a lot, but I think it's acceptable for now.

Delete report API

---

backend/src/AppServer.hs

Fix-ups from your comments on the admin APIs

Address PR feedback

---

backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Database.hs
backend/src/Types/Api.hs

remapPlayer API

---

backend/src/Database.hs
backend/src/Types/Database.hs

Cascading deletes

---

.vscode/settings.json
backend/Dockerfile
backend/bin/config.sh
backend/bin/deploy.sh
backend/bin/provision.sh
infrastructure/lib/infrastructure-stack.ts

Deploy with docker

---

frontend/src/GameReports.tsx
frontend/src/types.ts

Display log file download link in game reports table

---

frontend/src/PlayerEditForm.tsx
frontend/src/PlayerRemapForm.tsx
frontend/src/hooks/useConditionalActionEffect.tsx

DRY-ing up some code - can use this for the deletion form as well once it's on main

Add common hook for post-form-submission refresh

---

frontend/src/AdminFormLayout.tsx
frontend/src/FormElement.tsx
frontend/src/GameReportForm/index.tsx
frontend/src/PlayerEditForm.tsx
frontend/src/PlayerRemapForm.tsx
frontend/src/ReportDeleteForm.tsx

Just moves all the repeated form layout structure into one spot. The copy/pasting was bothering me 🫠

Admin form layout component

---

frontend/src/types.ts

Make frontend ProcessedGameReport type DRY

---

frontend/src/GameReportForm/initialFormData.tsx
frontend/src/PlayerEditForm.tsx
frontend/src/PlayerRemapForm.tsx
frontend/src/ReportDeleteForm.tsx
frontend/src/hooks/useFormData.tsx

More cleanup of repetitive code

Add helper fn for initializing form data

---

backend/src/Api.hs
backend/src/AppServer.hs

Make year an optional parameter

---

backend/bin/config.sh
backend/bin/deploy.sh
backend/bin/provision.sh
infrastructure/lib/infrastructure-stack.ts

Resolves #107 
Lemme know if you have any questions about the bash scripting / UNIX-y stuff!

Add persistent EBS storage

---

backend/src/AppServer.hs
backend/src/Types/DataField.hs
backend/src/Types/Migration.hs
frontend/src/GameReportForm/index.tsx
frontend/src/GameReports.tsx
frontend/src/constants.ts
frontend/src/hooks/useGameReportFormEffects.tsx
frontend/src/utils.tsx

Resolves #145 ~~(I don't know if you prefer to make this change at the data level, but this would be enough for MVP at least)~~

Display Rated/Unrated instead of Ranked/Unranked

---

backend/bin/deploy.sh

Does the deploy script still work for you after this change? (Maybe don't worry bout it til you're done with auth to avoid computer blowing up again)

Make docker build compatible with chelsea's mac

---

.vscode/settings.json
infrastructure/lib/infrastructure-stack.ts

Fix EBS persistence

---

frontend/src/GameReportForm/index.tsx
frontend/src/constants.ts
frontend/src/utils.tsx

Itty bitty start on frontend auth

Display specific auth error for 401 status code

---

frontend/src/LoadingOverlay.tsx
frontend/src/TableLayout.tsx

Add loading overlay to game reports and leaderboard

---

backend/src/AppServer.hs
backend/src/Database.hs

Algorithm specification doc: https://docs.google.com/document/u/0/d/1T2OIOfU9vlSJQd0xPoivFmHOUTvPOa1jjtaiN2vrHAQ/mobilebasic

League points algorithm

---

frontend/src/App.tsx
frontend/src/ButtonSelector.tsx
frontend/src/Leagues.tsx
frontend/src/Rankings.tsx
frontend/src/Table.tsx
frontend/src/TableLayout.tsx
frontend/src/constants.ts
frontend/src/styles/colors.ts
frontend/src/styles/sizes.ts
frontend/src/types.ts
frontend/src/utils.tsx

League frontend! Caveats: does not include the "add player" button yet or a free/shadow stats breakdown (will make issues for both, one MVP and one non-MVP). Going to add some comments below to check in with you on some choices.
```
const MOCK_STATS_SMALL: LeagueStats = {
1: {
name: "Frodo",
summary: {
wins: 1,
gameCount: 2,
points: 1.2,
},
gameStatsByOpponent: {
2: {
opponent: "Sam",
wins: 1,
losses: 0,
},
3: {
opponent: "Pippin",
losses: 1,
wins: 0,
},
},
},
2: {
name: "Sam",
summary: {
wins: 0,
gameCount: 1,
points: 0.1,
},
gameStatsByOpponent: {
1: {
opponent: "Frodo",
wins: 0,
losses: 1,
},
},
},
3: {
name: "Pippin",
summary: {
wins: 1,
gameCount: 1,
points: 1.1,
},
gameStatsByOpponent: {
1: {
opponent: "Frodo",
wins: 1,
losses: 0,
},
},
},
};
```

Leagues page

---

frontend/src/Leagues.tsx

Diff is mostly an indent change!

Sort league players by points

---

backend/app/Server.hs
backend/src/Api.hs
backend/src/AppServer.hs
backend/src/Types/Api.hs
backend/src/Types/Database.hs
frontend/src/App.tsx

Actually export tho

---

backend/app/Migration.hs
backend/src/Database.hs
backend/src/Types/Migration.hs

Links will be empty until the lift-n-shift script finishes, but they're correct!

Add report links and higher resolution times to migration

---

frontend/src/App.tsx

Add padding around edges of home page

---

frontend/src/GameReportForm/getInitialFormData.tsx

This is the thing we paired on, have 0% tested it because I'm lazy and waiting for the prod server to be fixed instead of running the server locally, ~so don't merge 😬~ nvm this is what draft PRs are for

Refactor getInitialFormData to be better

---

frontend/src/App.tsx
frontend/src/GameReportForm/index.tsx
frontend/src/Rankings.tsx

Per feedback from ladder managers
Resolves #206 
Resolves #205

Touch up some text

---

frontend/src/Autocomplete.tsx
frontend/src/PlayerRemapForm.tsx
frontend/src/Rankings.tsx
frontend/src/types.ts

Resolves #90 (cleanup while working on autocomplete for filtering/searching)

Generalize autocomplete option type

---

.gitignore
scripts/gamelog-migration/migration.py
scripts/gamelog-migration/pyproject.toml
scripts/gamelog-migration/uv.lock

May we never need to run this again :)
(Feel free to rubberstamp, just seemed good to check it in)

Add migration script for posterity

---

frontend/src/ButtonSelector.tsx
frontend/src/Leagues.tsx

Make selected league more obvious

---

frontend/src/Rankings.tsx

Cleans up appearance while flag images are loading:
| Original | New |
| - | - |
| ![image](https://github.com/user-attachments/assets/f6471c4c-aa82-4e1a-9ba6-528c80e9bc5b) | ![image](https://github.com/user-attachments/assets/4ffde659-6d87-47ed-96b9-97e933cac616) |

Add loading mask for flag images

---

backend/src/AppServer.hs

Fix incorrect S3 key naming

---

frontend/src/ToolsMenu.tsx

Two bugs:
- Login button mask doesn't work in prod; decided it's too hard to debug because the button behaves differently in prod vs. dev. Changed UI strategy
- An error shows up when you sign out, even though it actually succeeds. I needed to invert the logic of when to display an error, because after signing out, we expect the `userInfo` endpoint to return an error. I didn't see this in dev because we're faking auth in dev

Sign-in/sign-out button bug fixes

---

frontend/src/App.tsx
frontend/src/GameReports.tsx
frontend/src/types.ts

Load game reports in app root

---

frontend/src/GameReports.tsx
frontend/src/Leagues.tsx
frontend/src/Table.tsx
frontend/src/Table/FilterBar.tsx
frontend/src/Table/TableFilter.tsx
frontend/src/Table/index.tsx
frontend/src/Table/sumPriorWidths.tsx
frontend/src/Table/types.tsx
frontend/src/TableFilter.tsx
frontend/src/hooks/useMediaQuery.tsx
frontend/src/utils.tsx

~Such draft,~ very refactor
~WIP, just opening as a draft so I can review easier!~
Resolves #168
Resolves #96
Makes progress on #129
Will make #128 ~a lot~ a little? easier
Sorry for this. Diff is a lot. I'm pleased with my table now. The only significant **visible** difference is pinned columns (pinned through `pairing` on desktop and through `edit` on mobile), which is a nice win; the rest is invisible refactoring.
Screenshots of the column pinning:

Use custom table component for game reports
