sirrus233/wotr-community-website

frontend/src/GameReportForm.tsx, frontend/src/hooks/useFormData.tsx
To reduce file size. This makes `GameReportForm` responsible for the form's presentation and `useFormData` responsible for the form's state management. I copied the structure of the hook's return value (`[State, Meta, Helpers]`) from an npm package I like to use.
It's lost in the diff, but also renamed `controlledClearEffect` to `useControlledClearEffect` to be more React-y since it's a custom hook!
What do you think of the overall change? Does the splitting up make it hard to track the relationship between form state and presentation? These are some less nuclear alternatives I could do, which would still take good-sized chunks out of the `GameReportForm`:
- extract `initialFormData` into its own file
- extract `controlledClearEffect` and all its invocations into a smaller custom hook
=> Extract form state management into a custom hook

backend/src/AppServer.hs, backend/src/Database.hs
Change the monad context of the database helpers from `AppM` to just `IO`. This means we have to pass the connection explicitly, but makes it possible to group (what are now) IO actions into a single database transaction. We want our handlers to be able to do this, since they are frequently going to be making several queries which should either succeed or fail as a group.
Key new function is from `sqlite-simple` library:
> `withTransaction :: Connection -> IO a -> IO a`
Run an IO action inside a SQL transaction started with BEGIN TRANSACTION. If the action throws any kind of an exception, the transaction will be rolled back with ROLLBACK TRANSACTION. Otherwise the results are committed with COMMIT TRANSACTION.
Note: I suspect (but did not try) that we could keep the database functions …
=> Transaction support

frontend/tsconfig.json
I don't know the pros and cons of different module resolution strategies, but I noticed that with `bundler` TS doesn't throw a compile-time error when I've accidentally used a module in a file without importing it first, and changing to `nodenext` fixes that (and the accompanying change of `module` from `esnext` to `nodenext` was because TS told me I had to). Any opinion or just merge?
=> Use nodenext for tsconfig module resolution

backend/.vscode/settings.json, backend/src/Api.hs, backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, backend/src/Types/DataField.hs, backend/src/Types/Database.hs
This about does it for our basic implementation of submitting a report.
* We receive the report
* Insert players into the DB if necessary
* Insert the report into the DB
* Insert a row representing ratings diffs into the DB
I ended up walking away from storing ratings in the report table directly - kind of a headache. Check out the new schema, as well as the API's return type - see what you think!
=> Submitting a report modifies Elo

frontend/src/SelectNumericOptionInput.tsx
To fix a console error `Failed prop type: The prop value is marked as required in ForwardRef(StableOption), but its value is null`
This might be why you made the initial value `-1` originally! I like `null` remaining the true representation of "N/A" in form state, so what do you think of this as a middle ground?
=> Mask null in number input form control

frontend/src/GameReportForm.tsx, frontend/src/GameReportFormElement.tsx
Bandaid for the console error `Joy: A FormControl can contain only one control component (Autocomplete | Input | Textarea | Select | RadioGroup) You should not mix those components inside a single FormControl instance`
I don't love the boolean toggle I did, but I didn't want to to change the implementation of `MultiOptionInput` to use `Select` somehow and be a dropdown multiselect instead of the pretty buttons, and I didn't want a second version of `GameReportFormElement` that might get out of sync in presentation style with the original one, so it's what I landed on 🤷‍♀️ Is there a secret fourth option that would be better?
edit: I guess one more option is to discard the use of `FormControl` completely, but I like the styling it gives to the non-multi-select inputs when there's an error
=> Use FormControl wrapper only around single form controls

frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx, frontend/src/hooks/useFormData/initialFormData.tsx, frontend/src/types.ts
⚠️ *Does not include mapping of stronghold names to unspaced values* ⚠️
This does a bare minimum transformation of the form data into the schema expected by the server and allows a successful form submission as we saw earlier, hooray! Code-wise though, I was fighting for my life with types on this one and I don't know if what I landed on was the best solution? Will add more details in-line.
=> Map form data to a schematically valid HTTP payload

backend/.vscode/settings.json, backend/app/Main.hs, backend/src/Api.hs, backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, backend/src/Types/App.hs, backend/src/Types/DataField.hs, backend/src/Types/Database.hs, backend/src/Validation.hs, backend/wotr-community-website.cabal
I accidentally the server.
The big change here is from using the `sqlite-simple` library to the much more complex/powerful `persistent` library, alongside the companion library `esqueleto` (skeleton in Portuguese, I'm told). I was getting frustrated with how error prone the basic types provided by `sqlite-simple` were - things I would easily accept in any other language, but if we're going to be in Haskell, let's have nice things.
`persistent` is a general library for handling schematized storage in a type-safe way, it has many backends for different kinds of databases (we're still using the sqlite backend), handles schema migrations automagically, and all sorts of nice stuff. `esqueleto` allows for very powerful type-safe queries against the `persistent` database types.
I've had to touch …
=> Why not re-write the server

frontend/src/GameReportForm.tsx, frontend/src/SelectNumericOptionInput.tsx, frontend/src/SelectOptionInput.tsx, frontend/src/hooks/useFormData/index.tsx, frontend/src/types.ts
Tried to do the minimum amount of work on this I could! Next will be displaying an error message after a submission.
Uncovered a sneaky bug while adding the `resetForm` effect - the number inputs were uncontrolled components. Totally missed that before!
=> Display success message and reset game report form after submitting

backend/src/Types/DataField.hs, backend/src/Validation.hs, frontend/src/GameReportForm.tsx, frontend/src/VictoryPoints.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx, frontend/src/types.ts
Follow up on discussion in https://github.com/sirrus233/wotr-community-website/pull/33!
I tested different stronghold permutations and the server validation you added works great.
One side note, the server **disallows** reporting 10 shadow VP in case of a FPRV or SPRV - should it be **allowed** because a ring-based victory is checked first?
Also I labeled the new form control `What strongholds were captured by FP?` but do you think FP should be spelled out like Shadow is? And if so do people say `the Free Peoples` or just `Free Peoples`?
=> Collect FP strongholds in form and make expansion cities conditional

frontend/src/Rankings.tsx, frontend/src/types.ts
A lot of things about this PR are half-baked 😬 but I wanted us to be able to start seeing something before I called it quits!
This PR:
- Shows server-provided stats in a table
- Provides a "Refresh" button
Still left to do:
- Finish populating table with LoME, # FPMV, and tournament win stats
- The year 2024 is hard-coded for now; instead, should display a menu of years for user to choose from
- Make the table's first four columns sticky, like in the spreadsheet
- Add a filter for active vs. inactive players
- Styling, more of that?
- Code cleanup probably, it's not very DRY right now
=> Display partially populated leaderboard

backend/.vscode/settings.json, backend/bin/config.sh, backend/bin/deploy.sh, backend/bin/provision.sh, frontend/bin/deploy.sh, frontend/package-lock.json, infrastructure/lib/infrastructure-stack.ts
Adds some lovely helper scripts, now that we're ON THE INTERNET.
A deployment script for frontend and backend respectively, and a provisioning script to do all the first-time setup required if we ever swap out the EC2 instance.
There are some implicit requirements to run these:
`provision.sh`:
* Need credentials to ssh to the host as the `ec2-user`
`deploy.sh` (Backend flavor)
* Requires cabal
* Same ssh permissions that are required to provision
`deploy.sh` (Frontend flavor)
* Requires npm
* Requires aws-cli
* Requires access to the relevant AWS resources (s3+cloudfront), stored under a "wotrcommunity" profile
=> Deployment Scripts

backend/.vscode/settings.json, backend/src/Validation.hs, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx
Fixes this coming up as the result when a form doesn't meet ANY victory conditions
=> Bugfix - don't assume FPMV as default

frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/Rankings.tsx, frontend/src/TableView.tsx, frontend/src/types.ts
Once again did this a little quickly, so there's probably stuff missing, but initial pass!
Still left to do:
- We should audit the columns against the ones we want to keep from the spreadsheet
- I want to submit more variations of game reports to make sure all the variations of summarized values get displayed as intended
- Line wrapping in the table cells might be good since a line will just extend horizontally forever now
- I just realized frontend uses `comment` and backend uses `comments` in a game report haha...will fix that. Idk if submitting a form with a comment will break it because of that, haven't tried
- Game log field isn't populated yet obvs since that's not ready yet
=> Display game reports

frontend/src/GameReports.tsx
Laundry list of little styling improvements, just what I had time for before NYE! Unrelated, I might make a custom table component for us to use instead of MUI's provided `Table`. The visibly slow repainting (on initial load and on window resizing) is insanely aggravating.
- Lil' accent color bar for each row (which will pop even more once I make the first column(s) pinned/sticky)
- Styles each row's victory type as a colored badge
- Adds a silly emoji based on winning side
- Adds an initial column with a game number (numbering does not take pagination into account yet - left a `TODO` for that)
- Limits width of the `comments` column and allows comments to wrap to multiple lines
- Changes `<side> Concession` victory type to `<side> via Concession` because otherwise it reads like the …
=> Style game reports table a little bit

frontend/src/Rankings.tsx
Removes non-MVP columns as discussed, and a teeny fix to use `pid` for React component keys instead of player name.
=> Remove ladder columns LoME-onward

frontend/src/Rankings.tsx
Most of the red diff is just an indentation change and removal of  `entry.year === CURRENT_YEAR && ...` display logic 😬 feel free to merge or add commits to this whenever the backend breaking change is ready, if I'm not around! Otherwise will be on the lookout if this needs any coordinated changes.
Included 2023 and 2022 as disabled options just so 2024 wouldn't look too lonely up there.
=> Frontend ladder year selection

frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/Rankings.tsx, frontend/src/TableView.tsx, frontend/src/index.tsx, frontend/src/styles/colors.ts, frontend/src/styles/sizes.ts
- Changes certain elements which don't need to responsively resize (header, the ladder year selector, and the "refresh" button above tables) to have fixed heights, in order to responsively limit the ladder and game report tables to fit the remaining vertical screen space
- Pins row headers, which was enabled by bounding the table height
- The table `stickyHeader` prop only works on 2 levels of row headers before throwing up its hands and giving up, so I had to do a funky workaround to make all 3 row header levels of the ladder table sticky
- Adds a `styles` directory so there was a good place to keep the fixed heights required for these changes (in `sizes.ts`), and a little bit of scope creep to throw a `colors.ts` in the same place, so we can have common color palette to pull from
=> Limit ladder and game report table heights and make row headers sticky

frontend/src/Autocomplete.tsx, frontend/src/GameReportForm.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx
Converts player name fields into `Autocomplete`s, and displays a warning message above each one if you type a name that isn't present ✨
The player names are kind of mocked up, they're being retrieved from the `/leaderboard` endpoint with 2024 hard-coded just to have a substantial list of names displaying.
A good way to handle new players when there's time would be a `+ add new player` option inside the autocomplete, which would bring up a popup form to create a new player, and would send a POST request to a `/player` endpoint or something like that; then the new player would be merged into the `Autocomplete` options. After that we could add validation that player names MUST exist before submitting the form.
=> Auto-complete player names in game report form

backend/src/Types/Api.hs
Does what it says. A display name is set the first time a player is inserted into the database. This is sourced from either the 2022 data (if they existed then) or otherwise from however the first person to report it types it.
Since folks don't always report their own name (e.g. if they lose their first game), this is why it can be nice to allow admin-renaming. Coming soon!
=> Show nice display names

backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, backend/src/Types/Database.hs
A little jank, perhaps, but I think a reasonable middle ground to start with. This adds `isActive` to the leaderboard response, and provides a database function for updating the active status across the whole table. This only runs when reports are reprocessed.
I figure that's okay for MVP, since reports are reprocessed during migration. But eventually we may want to play around with scheduling this, or doing an update check for the involved players when a report is submitted.
=> Update active status when reprocessing reports

frontend/src/App.tsx, frontend/src/GameReportForm.tsx, frontend/src/Rankings.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx, frontend/src/hooks/useGameReportFormEffects.tsx, frontend/src/initialGameReportFormData.tsx, frontend/src/types.ts, frontend/src/utils.tsx
This is a beast sorry, it's mostly just shifting code around! I managed to split this up from the player-edit buttons change, so hopefully that makes it easier to review. Edit buttons will be out in a sec, on top of this branch.
This changes `useFormData` to be usable by any of our forms so the state management can be consistent.
- The hook was providing `GameReportForm` with a `/leaderboard` result in order to populate the `loser` and `winner` field autocompletion, so the `/leaderboard` request is now moved into `App`, which passes the result down to both `GameReportForm` and `Rankings` (which incidentally makes progress toward [#67](https://github.com/sirrus233/wotr-community-website/issues/67))
- The `controlledClearEffect` and other game-form-specific effect code is now in a separate …
=> Refactor useFormData hook to accept generic form data

frontend/src/Autocomplete.tsx, frontend/src/GameReportForm.tsx, frontend/src/GameReports.tsx, frontend/src/PlayerEditForm.tsx, frontend/src/PlayerRemapForm.tsx, frontend/src/Rankings.tsx, frontend/src/TableView.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx, frontend/src/types.ts
- On leaderboard page, adds an edit pencil/`PlayerEditForm` and merge icon/`PlayerRemapForm`, for editing a player's info and remapping a player, respectively
- Expands the `Autocomplete` to allow more complex options (I went with `(string | PlayerOption)[]` for right now, but really it should be more generic, like `(string | Option)[]` and then map `playerOptions` to the generic interface. That can always be improved upon when we need an autocomplete somewhere else, I just got tired
- For the `PlayerRemapForm`, when you click submit, it's a fake-out the first time, and a "danger" alert gets displayed. The alert tells you to click submit again if you're sure
- The input in both forms get the standard "Required" validation, and one layer on top of that, which disallows the input to match …
=> Frontend controls for editing and remapping of players

frontend/src/Filters.tsx, frontend/src/GameReports.tsx, frontend/src/Rankings.tsx, frontend/src/TableView.tsx, frontend/src/constants.ts, frontend/src/styles/sizes.ts, frontend/src/types.ts
Adds buttons above leaderboard table for filtering on active/inactive player status. Your API works great!
Includes a `Filters` component (a ripoff of `MultiOptionInput` for the most part) that we can reuse for more table filtering in the future.
Toggling between the filters is unbearably slow, MUI tables rendering performance strikes again 😬
=> Add filter buttons for player active status to leaderboard

backend/.vscode/settings.json, backend/app/Migration.hs, backend/app/Server.hs, backend/cabal.project, backend/src/Api.hs, backend/src/AppConfig.hs, backend/src/AppServer.hs, backend/src/Types/Api.hs, backend/src/Types/Database.hs, backend/src/Types/Migration.hs, backend/wotr-community-website.cabal, infrastructure/lib/infrastructure-stack.ts
Heck yeah let's gooo!
For frontend considerations, all that really matters is the API changes to `submitReport` and the associated request/response types.
As far as backend goes:
AWS actions operate with the help of an `Env` struct which I've now created during startup and then store in the Env of AppM. Once you're running, it's all just IO so pretty simple.
I've created a public readable bucket in our infrastructure - and the last thing I need to do is deploy putObject credentials to our host - the AWS library we're using should find those in the environment, but we'll need to test that actually happens.
=> Support submission of game logs

frontend/src/FileUpload.tsx, frontend/src/GameReportForm/index.tsx, frontend/src/GameReportForm/initialFormData.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData/index.tsx, frontend/src/hooks/useGameReportFormEffects.tsx, frontend/src/types.ts
- Collect file in a form control, input optional
- Change the payload format to `{ report, logFile }`
- Encode the payload as multipart form data before sending to the server
- Our `FormData` type had a naming conflict with the `FormData` web API, so I renamed our type to `GameFormData` (and changed `ValidFormData` to `ValidGameFormData` to match)
- Add new option to the `useFormData` input handler to validate a field **before** accepting the input (since we want to reject a file greater than the allowed size)
~~Server responds with a 415, which might be because backend change isn't deployed OR because the frontend request format is wrong, but either way here's a PR so we can look at it!~~ Update: made a fix, now a request without a log file succeeds, and with a log file fails, but it's a …
=> Collect game log file in game report form

frontend/src/GameReportForm/index.tsx, frontend/src/GameReports.tsx, frontend/src/PlayerEditForm.tsx, frontend/src/PlayerRemapForm.tsx, frontend/src/ReportDeleteForm.tsx, frontend/src/hooks/useFormData/index.tsx, frontend/src/types.ts, frontend/src/utils.tsx
Even though there's no input from the user, I still treated the whole thing as a form, so the code will look familiar to the player edit/remap code. The form's data is the `rid`, and is populated when the user clicks the report's deletion button.
Includes a little bit of supporting cleanup:
- add a default `toErrorMessage` util
- add a `displayTime` util
- passing in the post-form-submission success text as an argument to `useFormData` because previously all the success messages were saying "Report submitted" - oops
=> Game report deletion button

frontend/src/AdminFormLayout.tsx, frontend/src/App.tsx, frontend/src/ErrorDisplay.tsx, frontend/src/ExternalLink.tsx, frontend/src/GameReportForm/index.tsx, frontend/src/GameReports.tsx, frontend/src/Rankings.tsx, frontend/src/TableLayout.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData.tsx, frontend/src/utils.tsx
Includes a bug fix, leaderboard loading error was getting swallowed - oops!
The discord support link will only display alongside our default "Something went wrong." If it's something besides the default, I like the given error message standing on its own, because the error is already telling you what's wrong/how to fix the problem directly. If you disagree let me know and I'll include the discord link across the board! Easy to change
Resolves #94
=> Link to discord support in default error messages

backend/.vscode/settings.json, backend/app/Migration.hs, backend/app/Server.hs, backend/src/Types/Database.hs
Resolves #105 
* Migrations can now be run for the server by providing the "migrate" cmdline arg, but will not run otherwise
* Migrations always run for the Migration exe, but reduced duplication here
* Default set the AWS profile so we don't have to remember to do so
A little awkward that the migration script takes the whole environment when it only needs a logger and DB connection pool. But because of the way I structured the database operations as being inside `AppM` it can't be easily avoided. Not a huge deal, just annoying.
=> Remove mandatory migrate

backend/src/Api.hs, backend/src/AppServer.hs
Addresses the backend part of #112 
I can change this to a simpler query param of `page` that accepts just a number, but I figured the increased flexibility here might be nice, in case frontend would like to control how many results per page. LMK if you want it changed though!
=> Support pagination for getReports API

backend/src/AppServer.hs, backend/src/Types/Api.hs
Resolves #116 
Reports being reported in the wrong order has been known to happen, so we should support modification of report timestamp along with everything else. I didn't do this initially because timestamp isn't part of a Raw Report (which was basically our input type), but it turned out to be simple enough to add.
Not sure how the UI should support this. If it's hard, we could punt there if need-be.
One note on the frontend side, [per the documentation](https://hackage.haskell.org/package/text-iso8601-0.1.1/docs/Data-Time-FromText.html#v:parseUTCTime) the valid string-serialized forms of a UTCTime are:
> YYYY-MM-DD HH:MMZ
YYYY-MM-DD HH:MM:SSZ
YYYY-MM-DD HH:MM:SS.SSSZ
> The first space may instead be a T, and the second space is optional. The Z represents UTC. The Z may be replaced …
=> Support modificatin of report timestamp

backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Database.hs
Resolves #120 
(Note, this change will require a database migration in addition to a deployment of the server binary. Someday would be nice to be able to do this programmatically, but it's fine for now).
After profiling the times, I wouldn't call it revolutionary, but definitely worth doing. Measured runtime of a full reprocess dropped from ~13 seconds to ~ 9 seconds, which is about a 30% improvement.
I believe we can call this good, until/unless we need additional perf. So the following is just my musings on that problem:
-- 
Of the 9 seconds taken by a reprocess, they're split 4 / 5 between reading reports and processing them respectively. The 4 second time on reading is interesting, because it can't be reduced very easily with our current storage patterns, and is heavily CPU bound (the …
=> Create database indices

backend/app/Server.hs, backend/src/AppConfig.hs, backend/src/AppServer.hs, backend/src/Validation.hs, backend/wotr-community-website.cabal, frontend/src/FileUpload.tsx
Resolves #134 
Certainly not bulletproof, but I would argue good enough for now.
* On the frontent, accept text/plain or *.log extension files as input (I checked and confirmed it is Mac-specific nonsense going on with the logs. It knows they are text/plain, but browsers on Mac don't only get the MIME type. Mac has some notion of "hierarchy" that the browser is not aware of.)
* Block uploads > 1MB on the server
* Do a little bit of parsing validation on the backend, check at least for the header that should be present in all logs
=> Logfile Validation

backend/src/Api.hs, backend/src/AppServer.hs, backend/src/Auth.hs, backend/src/Database.hs, backend/src/Types/Api.hs, backend/src/Types/Auth.hs, backend/wotr-community-website.cabal
Finishes up the loose-ends from the initial auth PR
**Main additions**
* Logout API
* UserInfo API
`/logout` just nulls the sessionId in the auth database (recall that this is checked every time a protected action is attempted)
`/userInfo` returns a UserInfo response type... although this is quite boring at present, consisting of only a single `isAdmin` boolean - which should always be True if you get a successful response at all. We can use this to determine whether or not to show the admin controls on the page. The response can also be updated with more user info in the future, if that's ever needed.
**Other Refactor and Cleanup**
* Auth types moved to their own module, this solves some layering issues I had previously
* `UserId` and `SessionId` type aliases are now proper newtypes for …
=> Logout and UserInfo endpoints

backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, frontend/src/GameReports.tsx, frontend/src/Pagination.tsx
I touched the backend, sorry to intrude, felt super out of my depth 😬 I needed the total record count and did it inefficiently by calling `getAllGameReports`, which throws away any backend time savings from pagination. Hoping you can help me fix it?
Anyway, the main frontend part is the `Pagination` component! Not too complicated but the logic for displaying page ranges split by the `...`s was fun.
I did local testing by mocking props and the total page count mostly; once the server code is synced up I'll definitely do real-life testing to make sure page numbers are for sure lining up with reports.
=> Game reports frontend pagination

frontend/src/GameReports.tsx
First of a few pagination fixes - make the height of the page footer a fixed value, then add it to the calculation of available space for the reports table
=> Fix game reports page exceeding window height

frontend/src/App.tsx, frontend/src/GameReportForm/index.tsx, frontend/src/GameReports.tsx, frontend/src/GoogleLogin.tsx, frontend/src/PlayerEditForm.tsx, frontend/src/PlayerRemapForm.tsx, frontend/src/ReportDeleteForm.tsx, frontend/src/constants.ts, frontend/src/hooks/useFormData.tsx, frontend/src/networkErrorHandlers.ts, frontend/src/types.ts, frontend/src/utils.tsx
Expected behavior:
- If you're already signed in, the "signed in" message will be added to the header on mount if a request for your user info succeeds
- Otherwise, a successful sign-in with Google will kick off a new request for your user info, and the "signed in" message will be added to the header after the request succeeds
- If a user info request fails, nothing will be shown in the header
I couldn't do a full local E2E test, but I tested the UI by mocking out the Google button, and making my local server automatically validate auth requests without verification.
=> Display auth status in app header

backend/src/Api.hs, backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, backend/src/Types/DataField.hs, backend/src/Types/Database.hs
In the interest of managing complexity, this is sort of a partial PR. It adds APIs for adding a new league player, and querying the league stats (FYI I did change some field names, `wins` -> `totalWins` and `gameCount` -> `totalCount`)
TODO:
* The `points` value is not yet calculated, and will come in a follow-up PR
* Migrating existing league players from our CSV data will also come in a follow-up.
=> Add league player API

frontend/src/App.tsx
Temporary stopgap to prevent confusion until we have more time for #176
=> Put "admin" header above google sign-in

backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Database.hs
What happened today:
A player in league named `Sepp G` wanted a name change to `SeppG`. Not knowing how to do that properly, an admin added a new player to the league named `SeppG`. We now have both `Sepp G` and `SeppG` in the system.
Ordinarily, this would be fixed with a `remap` operation, remapping `Sepp G` to `SeppG`. But remap wasn't written to work with league data. This changes things so it can.
We must consider the case where the "new" player, the result of the remap, already exists and is present in league (such as the above example). Although it is easy to imagine scenarios where that may not be the case.
As an added bonus, this PR also speeds up reprocessing after remap, if the "from" player didn't actually play any games.
=> League delete remap

frontend/src/GameReportForm/index.tsx
Try to address #220 
Open to other thoughts here. See conversation: https://discord.com/channels/590789678890745857/818775910748258326/1340112563207405599
Having a perma-filled-in dummy value of "Ladder" next to the League/Tournament options might be a nicer way to illustrate this, rather than the additional text?
=> Try to clarify rated game reporting

backend/src/AppServer.hs
Resolves #226 
I shadow deployed this - I'm sorry!! But it was pretty trivial. You can now see that the highest rated, inactive player (PeterM) ranks below the lowest rated active player (TMAvenger).
(Promise to set up proper dev stuff soon!!)
=> Sort leaderboard by active first

frontend/src/Autocomplete.tsx
Noticed this bug in passing, which currently only impacts the `country` form field when editing a player. If you type in a country that doesn't exist, country is correctly updated to `null` in form state. However, the local input value continues to display the search string you typed. So it **looks** like when you submit the form, it allows you to enter a country that doesn't exist; in fact, you're deleting the player's country by sending `null`.
TLDR: syncs up the displayed input value—which we allow to temporarily depart from form state, while user is typing to search—with actual form state, on blur of the field.
=> Clear autocomplete text on blur if nothing valid selected

backend/src/Validation.hs
Should handle a few known cases where logfiles fail our validation:
* Windows style line endings
* Manually edited logs where passwords are inserted on the first lines
* Older client versions which can output some additional info prior to the "silent null" header we look for
=> More relaxed logfile validation

backend/src/Api.hs, backend/src/AppServer.hs, backend/src/Database.hs, backend/src/Types/Api.hs, frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/TableFilter.tsx, frontend/src/constants.ts, frontend/src/types.ts
Started with just winner, loser, and pairing filters! The league filter needs to go with either a new column or custom handling of mixed fields in the `Competition Type` column, and figured whatever change I make there doesn't need to hold up player filtering.
I want to reuse all this UI work for the leaderboard and league tables, but since I have a tables refactor coming up, I didn't worry about it yet - kept most of the work inside the `GameReports` file for now.
=> Add player filters to game reports page

backend/app/Migration.hs, backend/app/Server.hs, backend/src/Logging.hs
Resolves #106 
The Amazonka library (which handles all our AWS interactions for the backend) has its own logger, which doesn't interop with the logger we use for the rest of the app. This just provides a compatibility layer so that all the logging happens through our normal logger.
=> Amazonka logging

backend/src/Database.hs, frontend/src/App.tsx, frontend/src/Autocomplete.tsx, frontend/src/GameReports.tsx, frontend/src/PlayerRemapForm.tsx, frontend/src/TableFilter.tsx, frontend/src/types.ts
| No selections, closed | Open | After clicking "Any league" | After clicking "No league" | With selections, closed |
|-|-|-|-|-|
| ![image](https://github.com/user-attachments/assets/65c9491d-ebd1-4a31-a75f-e9478cffba9f) | ![image](https://github.com/user-attachments/assets/457d2c1f-98ee-4969-8ca3-36dbde9bf2c5) | ![image](https://github.com/user-attachments/assets/392b20e3-3168-47df-8823-fe196c5784c5) | ![image](https://github.com/user-attachments/assets/2379e660-68ab-48f9-8d53-8ded4919de93) | ![image](https://github.com/user-attachments/assets/e09b33b2-2a29-4d07-b049-bf9fa4bdf31b) |
- This was super quick to implement until I dove into the "any league" and "no league" options - hopefully establishing a pattern with this PR will make the other filters progressively faster!
- I didn't get …
=> Frontend leagues filter in game reports table

frontend/src/App.tsx, frontend/src/ErrorDisplay.tsx, frontend/src/ExternalLink.tsx, frontend/src/Modal.tsx, frontend/src/SupportLink.tsx, frontend/src/ToolsMenu.tsx, frontend/src/constants.ts, frontend/src/networkErrorHandlers.ts
Resolves #188
Resolves #175 
1. Move admin sign-in and export buttons into a header tools menu, and mask the google sign-in text with "admin sign-in":
2. Add logout:
3. Display related errors in clearable warning popups (instead of a persistent warning message in the header):
| | | |
|-|-|-|
| ![image](https://github.com/user-attachments/assets/7c220e6a-a83f-4556-afaf-1a5eef37086e) | ![image](https://github.com/user-attachments/assets/7deb9017-d663-4dde-b632-1acc028d224a) | ![image](https://github.com/user-attachments/assets/37520b01-c9aa-4976-bc5c-64a39ef2a234) |
Partially confirmed a logout request works, because it clears the session ID from my local database for a user "Frodo," which is the dummy user ID in `authHandlerDev`. But have no idea on the Google side of things via …
=> Tools menu + logout

frontend/src/ToolsMenu.tsx
Fixes header still showing "signed in" after a successful logout
=> Update signed-in status after logout

frontend/src/ToolsMenu.tsx
Loading spinner to fix a little flicker between the sign-in button and the success message after signing in
=> Add loading spinner in sign-in popup

frontend/src/App.tsx, frontend/src/GoogleLogin.tsx, frontend/src/Rankings.tsx, frontend/src/ToolsMenu.tsx, frontend/src/hooks/useRequestState.tsx, frontend/src/networkErrorHandlers.ts
Some groundwork before #67 - extracts some repetitive state management code into a hook before sticking similar state management for the 4th/last network call into the app root.
=> Extract repeated HTTP request state management into a hook

frontend/src/Autocomplete.tsx
Resolves #101 
Resolves #66 
UX improvement and a bug fix in one! Now as soon as an alert for an autocomplete form field is resolved, the alert will be cleared. Also, when you submit the game report form specifically, any alerts that were displaying before will be cleared as a result of resetting the form.
=> Clear autocomplete alert immediately when alert is resolved

frontend/src/Rankings.tsx
Resolves #113 
I want the longer term solution to be (1) do my planned tables refactor, (2) make the filter bar currently used by game reports a reusable component for the leaderboard table, (3) make `year` a filter in the leaderboard filter bar. But this should do in the meantime.
=> Move leaderboard year selector adjacent to yearly stats header

frontend/src/GameReportForm/index.tsx, frontend/src/MultiOptionInput.tsx
Resolves #220 I think! Displays a preselected button that says "ladder" when "rated" is chosen. The button is permanently selected, and isn't actually hooked up to state; it's purely for UX.
=> Display preselected "ladder" option for rated game type selection

frontend/src/App.tsx, frontend/src/GameReportForm/index.tsx, frontend/src/GameReports.tsx
Past Chelsea half-did this already 🎉 The existing refresh effect happens after submitting the report edit form. This expands that effect to include the rankings table, and to happen after both create + edit.
Resolves #130
=> Refresh other pages after submitting a game report

frontend/src/GameReports.tsx
Oops - if you add a filter **after** advancing pages and number of results is reduced such that the current page no longer exists, there appears to be zero results in the table, when in reality you're just in page limbo. This fix resets the page to 1 when a filter is changed.
=> Reset page to 1 when game report filters are changed

frontend/webpack.config.js
Came across code elsewhere where react router allowed a non-homepage refresh, immediately thought of us, then finally went down the config rabbit hole to find this!
=> Enable non-homepage refresh in development

frontend/src/GameReports.tsx
=> Add a more obvious filter icon next to filter bar expansion button

infrastructure/lib/infrastructure-stack.ts
It's not a ~great practice to have an open SSH port on a host. We restrict it down to our personal IPs to minimize risk, but that's annoying because our IPs change.
AWS has a session manager that gets around this and is the "right way" to do this when using EC2.
So this change:
* Closes port 22 on the host
* Adds SSM manageability to the EC2 isntance role
There needs to be an agent running on the host to receive SSM connections, but I believe that ships by default with the amazonlinux AMI we're using.
=> Close ssh port and add SSM to ec2 role

frontend/src/Leagues.tsx
Sorry, this is a bandaid while I figure out what's actually wrong
=> Bug fix - league player names column missing for non-admin

backend/app/Server.hs, backend/bin/config.sh, backend/bin/provision.sh, backend/src/Api.hs, backend/src/AppConfig.hs, backend/src/AppServer.hs, backend/src/Auth.hs, backend/src/Types/Auth.hs, backend/wotr-community-website.cabal
Resolves https://github.com/sirrus233/wotr-community-website/issues/238
This one really should've been done a while ago, but I had to build some new infrastructure to support what I wanted to do.
Before this change, we had `Authorized` and `Unauthorized` endpoints, based on whether or not the endpoint requires the user to be authenticated to call the API in question. This change introduces a third type of authorization.
`Authorized` has been renamed to `AuthorizedUser` and refers to an authorized human
`AuthorizedService` refers to a simpler auth scheme which just requires an API key in the header of the request, which can be provided by a scheduled service worker.
That will let us provide an endpoint that humans generally can't call, but our own server can use to call itself.
Having made …
=> Periodically update active player statuses

frontend/src/Leagues.tsx
My first fix was almost the right one, I just panicked a little bit. In short I was accidentally removing the league table first-column header for non-admins, when I should have just been making the content of the header blank. The previous fix accomplished that, but this is a cleaner way to do it
=> Adjust leagues table add-player button display logic

frontend/src/Table/index.tsx
=> Fix relatively positioned elements floating above table headers

frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/Table/AutocompleteFilter.tsx, frontend/src/Table/FilterBar.tsx, frontend/src/Table/InequalityFilter.tsx, frontend/src/Table/constants.tsx, frontend/src/Table/index.tsx, frontend/src/Table/types.tsx, frontend/src/types.ts
First frontend filter to go with your backend work 🎉 
This PR establishes a new UI component for inequality filtering, uses that new filter for the `turns` column, and refines types to make them smarter at telling what properties are allowed/needed based on context.
This is branched from a rebased version of your [filters](https://github.com/sirrus233/wotr-community-website/tree/filters) branch. Should we just merge yours even though it hasn't been fully tested so we don't get into a feature branch situation? I did quick regression checks of the existing filters and everything seems A-OK so far.
| Closed | Operator open | Turn open | Filter applied
| - | - | - | - |
| <img width="556" height="186" alt="image" src="https://github.com/user-attachments/assets/c109a3dc-6223-431d-ae6a-9f81fa075 …
=> Support frontend inequality filtering and add turns filter

frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/Table/AutocompleteFilter.tsx, frontend/src/Table/BooleanFilter.tsx, frontend/src/Table/FilterBar.tsx, frontend/src/Table/InequalityFilter.tsx, frontend/src/Table/ResetButton.tsx, frontend/src/Table/styledComponents.tsx, frontend/src/Table/types.tsx, frontend/src/types.ts
Game log column filter, underpinned by a `BooleanFilter` component which can be reused for the comments and treebeard columns.
| Initial | Menu open | "No log" selected | "Log" selected |
| - | - | - | - |
| <img width="159" height="79" alt="image" src="https://github.com/user-attachments/assets/5a9f645e-223c-4082-8738-60b45dc7d0aa" /> | <img width="171" height="140" alt="image" src="https://github.com/user-attachments/assets/863f82d5-eb84-4ecd-9243-395763efc8c1" /> | <img width="157" height="75" alt="image" src="https://github.com/user-attachments/assets/cc67e071-b545-4178-9394-e22b3fbd164d" /> | <img width="158" height="72" alt="image" src="https://github.com/user-attachments/assets/62cdde84-3fb4-443c-bb1c-37f5ff2ff5ff" />
=> Support frontend boolean filtering and add game log filter

frontend/src/App.tsx, frontend/src/GameReports.tsx, frontend/src/types.ts
Nothing unexpected came up, so following your #298 comment will merge this! If you want a change to the options text at all though (like "yes"/"no" instead of "mustered"/"not mustered" or something like that) let me know and I'll adjust 👍 
| Initial | Open menu | "Mustered" applied | "Not mustered" applied |
| - | - | - | - |
| <img width="165" height="73" alt="image" src="https://github.com/user-attachments/assets/97dfc30a-9594-4199-8238-e0e36e72f355" /> | <img width="171" height="131" alt="image" src="https://github.com/user-attachments/assets/ebfe4347-7154-48b7-911c-b63038efe591" /> | <img width="169" height="107" alt="image" src="https://github.com/user-attachments/assets/e1b70a37-c76c-424e-bc7b-086c7d9f4d17" /> | <img width="161" height="80" alt="image" …
=> Frontend treebeard filter
